apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
#  labels:
#    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: grafana-admin-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  externalSecretName: grafana-admin-credentials
  namespaceSelectors:
  - matchLabels:      
      kubernetes.io/metadata.name: argocd
  refreshTime: "10s"
  externalSecretSpec:
    refreshInterval: "15s"
    secretStoreRef:
      name: openbao-backend
      kind: ClusterSecretStore
    target:
      name: grafana-admin-credentials # K8s secret name
      creationPolicy: Owner
    # To get single key/value(s)
    data:
      - secretKey: admin-user # Key to create in the K8s secret
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: talos-pve/grafana-admin-credentials # Path to the secret
          metadataPolicy: None
          property: admin-user # Key of the Vault secret to copy
      - secretKey: admin-password # Key to create in the K8s secret
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: talos-pve/grafana-admin-credentials # Path to the secret
          metadataPolicy: None
          property: admin-password # Key of the Vault secret to copy
