kubeControllerManager:
  endpoints:
    - 10.0.0.1
    - 10.0.0.2
    - 10.0.0.3

kubeEtcd:
  endpoints:
    - 10.0.0.1
    - 10.0.0.2
    - 10.0.0.3
  service:
    selector:
      component: etcd

kubeScheduler:
  endpoints:
    - 10.0.0.1
    - 10.0.0.2
    - 10.0.0.3
