apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    gethomepage.dev/href: "https://alertmanager.urbaman.cloud"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Alertmanager Alert System"
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: alertmanager.svg
    gethomepage.dev/app: alertmanager # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: "Alertmanager"
    #gethomepage.dev/showStats: "true"
    #gethomepage.dev/widget.type: "grafana"
    #gethomepage.dev/version: "2"
    #gethomepage.dev/alerts: alertmanager
    #gethomepage.dev/widget.url: "https://grafana.urbaman.cloud"
    #gethomepage.dev/pod-selector: ""
    #gethomepage.dev/weight: 10 # optional
    #gethomepage.dev/instance: "public" # optional
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`alertmanager.urbaman.cloud`)
      services:
      - name: kube-prometheus-stack-alertmanager
        port: 9093
        serversTransport: alertmanager
      middlewares:
        - name: security
          namespace: traefik
  tls:
    secretName: alertmanager-urbaman-cloud    
    options:
      name: tlsoptions
      namespace: traefik