apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    gethomepage.dev/href: "https://grafana.urbaman.cloud"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Grafana Monitoring Dashboards"
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: grafana.svg
    gethomepage.dev/app: grafana # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: "Grafana"
    #gethomepage.dev/showStats: "true"
    gethomepage.dev/widget.type: "grafana"
    gethomepage.dev/widget.version: "2"
    gethomepage.dev/widget.alerts: "alertmanager"
    gethomepage.dev/widget.url: "https://grafana.urbaman.cloud"
    gethomepage.dev/widget.username: GRAFANA_USERNAME
    gethomepage.dev/widget.password: GRAFANA_PASSWORD
    #gethomepage.dev/pod-selector: ""
    #gethomepage.dev/weight: 10 # optional
    #gethomepage.dev/instance: "public" # optional
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`grafana.urbaman.cloud`)
      services:
      - name: kube-prometheus-stack-grafana
        port: 80
        serversTransport: grafana
      middlewares:
        - name: security
          namespace: traefik
  tls:
    secretName: grafana-urbaman-cloud
    options:
      name: tlsoptions
      namespace: traefik