apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-grafana
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    customFrameOptionsValue: "SAMEORIGIN"
    contentSecurityPolicy: >-
      default-src 'self';
      script-src 'self';
      connect-src 'self';
      img-src 'self';
      style-src 'self' 'unsafe-inline';
      object-src 'none';
      base-uri 'none';
      frame-ancestors 'self' https://ceph-dashboard.urbaman.cloud;
    customResponseHeaders:
      server: ""
      x-powered-by: ""