apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cilium-hubble-urbaman-cloud
  namespace: kube-system
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - cilium-hubble.urbaman.cloud
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: cilium-hubble-urbaman-cloud