apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-urbaman-cloud
  namespace: argocd
spec:
  # Certificate will be valid for these domain names
  dnsNames:
  - argocd.urbaman.cloud
  # Reference our issuer
  # As it's a ClusterIssuer, it can be in a different namespace
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-acme-issuer
  # Secret that will be created with our certificate and private keys
  secretName: argocd-urbaman-cloud